- name: maven
  container:
  image: eclipse/maven-jdk8:latest
  volumeMounts:
    - name: mavenrepo
      path: /root/.m2
    env:
      - name: ENV_VAR
        value: value
    endpoints:
      - name: maven-server
        targetPort: 3101
        protocol: https
        secure: 'true'
        exposure: public
    memoryRequest: 256M
    memoryLimit: 1536M
    cpuRequest: 0.1
    cpuLimit: 0.5
    command: ['tail']
    args: ['-f', '/dev/null']