#!/bin/bash

rm .env

echo "REACT_APP_BUILDER_API_URL=$REACT_CONFIG_AZBUILDER_URL" >> .env;
echo "REACT_APP_CLIENT_ID=$REACT_CONFIG_CLIENT_ID" >> .env;
echo "REACT_APP_AUTHORITY=$REACT_CONFIG_AUTHORITY" >> .env;
echo "REACT_APP_REDIRECT_URI=$REACT_CONFIG_REDIRECT" >>.env;