blank_issues_enabled: false
contact_links:
  - name: Community
    url: https://join.slack.com/t/terrakubeworkspace/shared_invite/zt-2cx6yn95t-2CTBGvsQhBQJ5bfbG4peFg
    about: Please ask and answer usage questions here.