issuer: https://terrakube-dex.platform.local/dex

storage:
  type: memory
web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

oauth2:
  responseTypes: ["code", "token", "id_token"]

connectors:
  - type: ldap
    name: OpenLDAP
    id: ldap
    config:
      # The following configurations seem to work with OpenLDAP:
      #
      # 1) Plain LDAP, without TLS:
      host: terrakube-ldap-service:1389
      insecureNoSSL: true
      insecureSkipVerify: true
      #
      # 2) LDAPS without certificate validation:
      #host: localhost:636
      #insecureNoSSL: false
      #insecureSkipVerify: true
      #
      # 3) LDAPS with certificate validation:
      #host: YOUR-HOSTNAME:636
      #insecureNoSSL: false
      #insecureSkipVerify: false
      #rootCAData: 'CERT'
      # ...where CERT="$( base64 -w 0 your-cert.crt )"

      # This would normally be a read-only user.
      bindDN: cn=admin,dc=example,dc=org
      bindPW: admin

      usernamePrompt: Email Address

      userSearch:
        baseDN: ou=users,dc=example,dc=org
        filter: "(objectClass=person)"
        username: mail
        # "DN" (case sensitive) is a special attribute name. It indicates that
        # this value should be taken from the entity's DN not an attribute on
        # the entity.
        idAttr: DN
        emailAttr: mail
        nameAttr: cn

      groupSearch:
        baseDN: ou=Groups,dc=example,dc=org
        filter: "(objectClass=groupOfNames)"

        userMatchers:
          # A user is a member of a group when their DN matches
          # the value of a "member" attribute on the group entity.
          - userAttr: DN
            groupAttr: member

        # The group name should be the "cn" value.
        nameAttr: cn

staticClients:
  - id: example-app
    redirectURIs:
      - "https://terrakube.platform.local"
      - "https://terrakube-api.platform.local"
      - "https://terrakube-dex.platform.local"
      - "/device/callback"
      - "http://localhost:10000/login"
      - "http://localhost:10001/login"
    name: "Example App"
    #secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    public: true