name: Release Terrakube

on: 
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [jammy, jammy-arm, alpaquita]
    env:
      VERSION: ${{ github.event.release.tag_name }}
    runs-on: ${{ matrix.os == 'jammy-arm' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Set environment label for Alpaquita
      if: matrix.os == 'alpaquita'
      run: echo "VERSION=${{ env.VERSION }}-alpaquita" >> $GITHUB_ENV

    - name: Set environment label for Jammy-ARM
      if: matrix.os == 'jammy-arm'
      run: echo "VERSION=${{ env.VERSION }}-arm" >> $GITHUB_ENV

    - name: Update POM Version
      run: mvn versions:set-property -Dproperty=revision -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false

    - name: Build Image with Maven
      run: |
        if [ "${{ matrix.os }}" == "alpaquita" ]; then
          mvn -pl "api,registry,executor" spring-boot:build-image -B --file pom.xml -Dmaven.test.skip=true -Dbuildpack.builder=bellsoft/buildpacks.builder:glibc
        elif [ "${{ matrix.os }}" == "jammy-arm" ]; then
          mvn -pl "api,registry,executor" spring-boot:build-image -B --file pom.xml -Dmaven.test.skip=true -Dbuildpack.builder=dashaun/builder-arm:20240403
        else
          mvn -pl "api,registry,executor" spring-boot:build-image -B --file pom.xml -Dmaven.test.skip=true
        fi
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Tag and Push Executor Images
      run: |
        IMAGE_ID=$(docker images executor -q)
        docker tag $IMAGE_ID azbuilder/executor:${{ env.VERSION }}
        docker tag $IMAGE_ID azbuilder/executor:latest
        docker push azbuilder/executor:${{ env.VERSION }}
        docker push azbuilder/executor:latest

    - name: Tag and Push API Images
      run: |
        IMAGE_ID=$(docker images api-server -q)
        docker tag $IMAGE_ID azbuilder/api-server:${{ env.VERSION }}
        docker tag $IMAGE_ID azbuilder/api-server:latest
        docker push azbuilder/api-server:${{ env.VERSION }}
        docker push azbuilder/api-server:latest

    - name: Tag and Push Registry Images
      run: |
        IMAGE_ID=$(docker images open-registry -q)
        docker tag $IMAGE_ID azbuilder/open-registry:${{ env.VERSION }}
        docker tag $IMAGE_ID azbuilder/open-registry:latest
        docker push azbuilder/open-registry:${{ env.VERSION }}
        docker push azbuilder/open-registry:latest

    - name: Build and Push UI Images
      if: matrix.os == 'jammy' || matrix.os == 'jammy-arm'
      working-directory: ./ui
      run: |
        docker build --build-arg REACT_APP_TERRAKUBE_VERSION=v${{ env.VERSION }} -t azbuilder/terrakube-ui:latest -t azbuilder/terrakube-ui:${{ env.VERSION }} --push .